apiVersion: v1
clusters:
- cluster:
    server: https://<kubernetes-api-server-url>  # Replace with your cluster's API server URL
    insecure-skip-tls-verify: true
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
    namespace: default
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    token: <your-token>  # Replace with the actual token
