apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <base64-encoded-ca-cert>  # Replace with your CA cert data
    server: https://<kubernetes-api-server-url>  # Replace with your cluster's API server URL
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
    namespace: default
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    token: <your-token>  # Replace with the actual token
